name: Extract OpenAPI Schema

on:
  pull_request:
    branches: [ main ]

jobs:
  extract-openapi:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: Checkout PR Branch
        run: |
          PR_BRANCH=$(gh pr view ${{ github.event.pull_request.number }} --json headRefName -q .headRefName)
          git fetch origin $PR_BRANCH
          git checkout $PR_BRANCH
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Generate OpenAPI JSON
        run: |
          # python -c "import json; from main import app; print(json.dumps(app.openapi()))" > openapi.json
          python -c "import json; from main import app; print(json.dumps(app.openapi(), indent=2, sort_keys=True))" > openapi.json
          cat openapi.json

      - name: Commit OpenAPI JSON
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add openapi.json
          git commit -m "Update OpenAPI schema" || echo "No changes to commit"
          git log
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
